version: '3.8'

services:
  # Main API service
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./music:/app/music
      - ./samples:/app/samples
      - ./database:/app/database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Background statistics worker
  stats-updater:
    build: .
    command: ["python", "stats_updater_runner.py"]
    env_file:
      - .env
    restart: unless-stopped

# No volumes needed since we're using external databases